import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import TopNav from "@/Components/TopNav";
import Header from "@/Components/Header";
import Footer from "@/Components/Footer";

const inter = Raleway({ subsets: ["latin"] ,weight: ["300","400","500","600", "700","800","900"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} overflow-x-hidden`}>
        <Header />
        <main>{children}</main>
        <Footer/>
      </body>
    </html>
  );
}
